name: Build, Test and Deploy

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  version-check:
    uses: kokoichi206/utils/.github/workflows/android-version-check.yml@main

  build:
    # HEADコミットが'skip ci'を含んでいれば、ciをキャンセルする。
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    uses: kokoichi206/utils/.github/workflows/android-build.yml@main

  local-test:
    needs: [ version-check, build ]
    uses: kokoichi206/utils/.github/workflows/android-local-test.yml@main

  android-emulator-test:
    needs: [ version-check, build ]
    uses: kokoichi206/utils/.github/workflows/android-emulator-test.yml@main
